First Manager implementation
Friedchicken-42/progettoIngegneriaSoftware pull request #8
Opened 2024-12-04 21:10 UTC by Friedchicken-42

## Summary

- [x] Updated database to async execution
- [x] Added `Manager` class and `run` for async functions
- [x] Connected favourites to the database
- [ ] Connected search to the API

2024-12-07 10:21 UTC, Friedchicken-42 commented on app/src/main/java/com/example/ecodigify/ui/search/SearchFragment.kt
> +                }
```suggestion
                for (i in ingredients.indices) {
                    val itm = popFilterMenu.menu.add(
                        Menu.NONE,
                        i,
                        Menu.NONE,
                        ingredients[i].name
                    )
                    itm.isCheckable = true
                    itm.isChecked = true
                }
```
Questo potrebbe fixare il cast, in caso possiamo aggiungere che `ingredientGetAll` li ritorni ordinati

2024-12-10 12:06 UTC, saccarosium requested changes
In fatto di funzionalità ci siamo. Ci sono piccolezze che conviene modificare ma sembra tutto apposto.

2024-12-10 13:26 UTC, Friedchicken-42 commented on app/src/main/java/com/example/ecodigify/Manager.kt
> +// Callback-based async executor
faremo più avanti

2024-12-10 13:32 UTC, Friedchicken-42 reviewed
resolved

2024-12-10 13:33 UTC, merged